# Определение версии Docker Compose и начало описания сервисов
version: '3'

services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
     - 6379:6379
    volumes:
     - $PWD/redis-data:/var/lib/redis
     - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master
    networks:
      node_net:
        ipv4_address: 172.28.1.4
  postgres_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      node_net:
        ipv4_address: 172.28.1.5
  pgadmin:
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
        PGADMIN_DEFAULT_PASSWORD: password
        PGADMIN_LISTEN_PORT: 80
    ports:
        - 15432:80
    networks:
      internet:
      node_net:
        ipv4_address: 172.28.1.6
  spiderapi:
    build: 
      context: .
      dockerfile:  ./spider_app/Dockerfile
    command: uvicorn main:app_spider --reload --port 8000 --host 0.0.0.0
    ports:
      - 8000:8000
    networks:
      internet:
      node_net:
        ipv4_address: 172.28.1.3
networks:
  node_net:
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
  internet:
    ipam:
      driver: default